import test from 'node:test';
import assert from 'node:assert/strict';
import { LIMITS, parseCSV, detectMapping, detectSemantics, parseDate, normalise, priceRow, filterRows, summarise, csvCell, exportCSV, demoData } from '../src/engine.js';
const header = 'date,model,input_tokens,cached_input_tokens,cache_write_tokens,output_tokens,cost_usd,currency\n';
const load = (body, prefix = header) => normalise(parseCSV(prefix + body));
const row = { date: '2026-09-01', model: 'custom-model', fresh: 1000000, cached: 500000, written: 100000, output: 200000, cost: null, sourceRow: 2 };
const rates = new Map([['custom-model', { fresh: '2', cached: '0.2', written: '2.5', output: '8' }]]);

test('simple CSV preserves zero values', () => assert.equal(load('2026-09-01,m,0,0,0,0,0,USD').rows[0].cost, 0));
test('quoted commas and escaped quotes', () => { const p = parseCSV('a,b\n"one, two","three ""four"""'); assert.deepEqual(p.records[0], ['one, two', 'three "four"']); });
test('BOM, CRLF and blank lines', () => assert.equal(parseCSV('\uFEFFa,b\r\n1,2\r\n\r\n').records.length, 1));
test('multiline quoted fields', () => assert.equal(parseCSV('a,b\n"first\nsecond",2').records[0][0], 'first\nsecond'));
test('tab detection ignores delimiters in quotes', () => assert.equal(parseCSV('date\tmodel\n2026-09-01\t"a,b;c"').delimiter, '\t'));
test('semicolon delimiter', () => assert.equal(parseCSV('a;b\n1;2').delimiter, ';'));
test('trailing empty fields', () => assert.deepEqual(parseCSV('a,b,c\n1,2,').records[0], ['1', '2', '']));
test('unclosed quotes rejected', () => assert.throws(() => parseCSV('a,b\n"bad,2'), /unclosed/));
test('malformed quote inside unquoted field rejected', () => assert.throws(() => parseCSV('a,b\nx"y,2'), /quoting/));
test('text following closing quote rejected', () => assert.throws(() => parseCSV('a,b\n"a"x,2'), /quoting/));
test('empty file rejected', () => assert.throws(() => parseCSV(' \n'), /empty/));
test('header only rejected', () => assert.throws(() => parseCSV('a,b'), /data row/));
test('empty header rejected', () => assert.throws(() => parseCSV('a,\n1,2'), /unique/));
test('normalised duplicate headers rejected', () => assert.throws(() => parseCSV('Input Tokens,input_tokens\n1,2'), /unique/));
test('oversized file rejected before parsing', () => assert.throws(() => parseCSV('x'.repeat(LIMITS.bytes + 1)), /10 MB/));
test('too many columns rejected', () => assert.throws(() => parseCSV(Array(101).fill('x').join(',') + '\n1'), /100 columns/));
test('too many rows rejected', () => assert.throws(() => parseCSV('a,b\n' + '1,2\n'.repeat(50001)), /50,000/));
test('alias detection', () => assert.deepEqual(detectMapping(['Timestamp', 'Model Name', 'prompt_tokens', 'completion_tokens']).input, 2));
test('OpenAI-style inclusive cache avoids double counting', () => { const r = load('2026-09-01,m,100,30,10,20,,USD').rows[0]; assert.equal(r.fresh, 60); assert.equal(summarise([r]).tokens, 120); });
test('Anthropic-style fresh input sums caches separately', () => { const p = parseCSV('date,model,input_tokens,cache_read_input_tokens,cache_creation_input_tokens,output_tokens\n2026-09-01,m,60,30,10,20'); assert.equal(detectSemantics(p.headers), 'exclusive'); assert.equal(summarise(normalise(p).rows).tokens, 120); });
test('manual cache convention override', () => { const p = parseCSV(header + '2026-09-01,m,60,30,10,20,,USD'); assert.equal(normalise(p, detectMapping(p.headers), 'exclusive').rows[0].fresh, 60); });
test('cache cannot exceed inclusive input', () => assert.equal(load('2026-09-01,m,10,11,0,2,,USD').errors.length, 1));
test('required mapping validation', () => assert.throws(() => normalise(parseCSV('model,cost\nm,2')), /Map Date/));
test('column may not be used twice', () => { const p = parseCSV(header + '2026-09-01,m,1,0,0,2,,USD'); const m = detectMapping(p.headers); m.output = m.input; assert.throws(() => normalise(p, m), /once/); });
test('invalid row widths are reported', () => assert.match(load('2026-09-01,m,1').errors[0].message, /columns/));
test('negative tokens rejected', () => assert.equal(load('2026-09-01,m,-1,0,0,2,,USD').rows.length, 0));
test('fractional tokens rejected', () => assert.equal(load('2026-09-01,m,1.1,0,0,2,,USD').rows.length, 0));
test('non-finite values rejected', () => assert.equal(load('2026-09-01,m,Infinity,0,0,2,,USD').errors.length, 1));
test('missing both token counts rejected', () => assert.equal(load('2026-09-01,m,,0,0,,,USD').errors.length, 1));
test('grouped integer tokens accepted', () => assert.equal(load('2026-09-01,m,"1,000",0,0,2,,USD').rows[0].fresh, 1000));
test('malformed digit grouping rejected', () => assert.equal(load('2026-09-01,m,"10,00",0,0,2,,USD').errors.length, 1));
test('invalid and valid rows are separated', () => { const r = load('bad,m,10,0,0,2,,USD\n2026-09-01,m,10,0,0,2,,USD'); assert.equal(r.rows.length, 1); assert.equal(r.errors[0].row, 2); });
test('duplicates flagged but retained', () => { const r = load('2026-09-01,m,10,0,0,2,,USD\n2026-09-01,m,10,0,0,2,,USD'); assert.equal(r.duplicates, 1); assert.equal(r.rows.length, 2); });
test('unsupported currency never silently relabelled', () => assert.equal(load('2026-09-01,m,10,0,0,2,1,GBP').errors.length, 1));
test('missing price remains null', () => assert.equal(load('2026-09-01,m,10,0,0,2,,USD').rows[0].cost, null));
test('prototype-like model keys safe', () => { const s = summarise([{ ...row, model: '__proto__', cost: 1 }]); assert.equal(s.models[0].name, '__proto__'); assert.equal(s.cost, 1); });
test('ISO dates accepted', () => assert.equal(parseDate('2026-09-30'), '2026-09-30'));
test('ISO timezone is normalised to UTC', () => assert.equal(parseDate('2026-09-30T23:30:00-02:00'), '2026-10-01'));
test('unix timestamps seconds and milliseconds agree', () => assert.equal(parseDate('1790798400'), parseDate('1790798400000')));
test('ambiguous local dates rejected', () => assert.throws(() => parseDate('09/10/2026')));
test('timezone-free timestamp rejected', () => assert.throws(() => parseDate('2026-09-30T10:00:00')));
test('impossible calendar dates rejected', () => assert.throws(() => parseDate('2026-02-30')));
test('leap day accepted only in leap year', () => { assert.equal(parseDate('2024-02-29'), '2024-02-29'); assert.throws(() => parseDate('2026-02-29')); });
test('category costs calculated separately', () => assert.ok(Math.abs(priceRow(row, rates).cost - 3.95) < 1e-10));
test('recorded cost takes precedence', () => assert.deepEqual(priceRow({ ...row, cost: 7 }, rates), { cost: 7, basis: 'recorded' }));
test('recorded zero is not treated as absent', () => assert.equal(priceRow({ ...row, cost: 0 }, rates).cost, 0));
test('unknown model is unpriced not free', () => assert.deepEqual(priceRow(row), { cost: null, basis: 'unpriced' }));
test('missing required category invalidates row estimate', () => assert.equal(priceRow(row, new Map([['custom-model', { fresh: 2, output: 8 }]])).cost, null));
test('zero-volume categories do not require rates', () => assert.equal(priceRow({ ...row, cached: 0, written: 0 }, new Map([['custom-model', { fresh: 2, output: 8 }]])).cost, 3.6));
test('explicit zero rates are permitted', () => assert.equal(priceRow(row, new Map([['custom-model', { fresh: 0, cached: 0, written: 0, output: 0 }]])).cost, 0));
test('blank rates are not zero rates', () => assert.equal(priceRow(row, new Map([['custom-model', { fresh: '', cached: 0, written: 0, output: 0 }]])).cost, null));
test('negative rates invalid', () => assert.equal(priceRow(row, new Map([['custom-model', { fresh: -1 }]])).cost, null));
test('filtering by model and date is inclusive', () => { const { rows } = demoData(); assert.equal(filterRows(rows, { model: 'swift-small', from: '2026-09-01', to: '2026-09-03' }).length, 3); });
test('empty date range returns no rows', () => assert.equal(filterRows([row], { from: '2026-10-01', to: '2026-09-01' }).length, 0));
test('mixed coverage retains unknown token totals', () => { const s = summarise([row, { ...row, model: 'unknown' }], rates); assert.equal(s.unpriced, 1); assert.equal(s.coverage, .5); assert.equal(s.tokens, 3600000); });
test('empty summary is finite', () => { const s = summarise([]); assert.equal(s.tokens, 0); assert.equal(s.coverage, 0); assert.equal(s.cost, 0); });
test('demo is deterministic and fully priced', () => { const d = demoData(); assert.equal(d.rows.length, 63); assert.equal(summarise(d.rows, d.rates).coverage, 1); assert.deepEqual(demoData().rows, d.rows); });
test('CSV model cells cannot become spreadsheet formulas', () => { assert.equal(csvCell('=WEBSERVICE("x")').startsWith('"\''), true); assert.equal(csvCell(' \t@SUM(A1)').startsWith('"\''), true); });
test('CSV escaping quotes and newlines', () => assert.equal(csvCell('a,"b"\nc'), '"a,""b""\nc"'));
test('export records pricing basis and unknown costs', () => { const p = parseCSV(exportCSV([row], new Map())); assert.equal(p.records[0][6], ''); assert.equal(p.records[0][7], 'unpriced'); });
test('export total input round-trips without double counting', () => { const out = normalise(parseCSV(exportCSV([row], rates))).rows[0]; assert.equal(out.fresh, row.fresh); assert.equal(out.cached, row.cached); assert.equal(out.written, row.written); });
test('estimated export preserves provenance on re-import', () => { const out = normalise(parseCSV(exportCSV([row], rates))).rows[0]; assert.equal(priceRow(out).basis, 'estimated'); });
test('recorded export preserves provenance on re-import', () => { const out = normalise(parseCSV(exportCSV([{ ...row, cost: 1 }], rates))).rows[0]; assert.equal(priceRow(out).basis, 'recorded'); });
test('small scientific cost numbers round-trip', () => { const p = new Map([['custom-model', { fresh: 0.0000000001, cached: 0, written: 0, output: 0 }]]); const r = normalise(parseCSV(exportCSV([row], p))); assert.equal(r.errors.length, 0); assert.equal(r.rows[0].cost, 1e-10); });
test('invalid clock times rejected', () => { assert.throws(() => parseDate('2026-09-30T24:00:00Z')); assert.throws(() => parseDate('2026-09-30T12:60:00Z')); });
test('leading blank lines do not break delimiter detection', () => assert.equal(parseCSV('\n \ncol1;col2\n1;2').delimiter, ';'));
test('distinct model count bounded for safe UI rendering', () => { const r = load(Array.from({ length: 101 }, (_, i) => `2026-09-01,m${i},10,0,0,2,,USD`).join('\n')); assert.equal(r.rows.length, 100); assert.equal(r.errors.length, 1); });
test('contradictory cost basis rejected', () => { const p = parseCSV('date,model,input_tokens,cost_usd,cost_basis\n2026-09-01,m,1,3,unpriced'); assert.equal(normalise(p).errors.length, 1); });
